### ISSUE TITLE
What about IE?

### ISSUE THREAD

**Issue by berdof** [makeomatic/redux-connect#1]
In original redux-async-connect there is this PR.
https://github.com/Rezonans/redux-async-connect/pull/64

Maybe we should add it to the redux-connect? #

**Comment by AVVS** [comment]
Let me test it today and see the difference in compiled code

**Comment by AVVS** [comment]
@berdof I've updated code to enable es2015-loose preset, but I highly doubt you are having issues with this in IE10 because of previous preset. If you read through the comments on the issue that was posted - it was HMR that caused it.

https://github.com/makeomatic/redux-connect/commit/1fdbbce18e1122b0d5572e40799a86cd85a3536f is for reference. Please close the issue if it solves this for you or provide more input so that it can be addressed

**Comment by AVVS** [comment]
@berdof I will be marking this as closed, but feel free to open it again if you have more info
