### ISSUE TITLE
Sequence of promises

### ISSUE THREAD

**Issue by ronar** [makeomatic/redux-connect#115]
First of all, thanks for good work. I was struggling much when tried to set this library up for universal rendering (documentation requires little improvements 😅 and maybe I'll help you with that later).

A little question:
```javascript
module.exports = asyncConnect(
    [{
        key: 'products',
        promise: ({params, store: {dispatch, getState}}) => {
            return dispatch(fetchProducts())
                .then(data => {
                    const someValues = reduce(data.products, (values, product) => {
                        if (product.products.length) {
                            ...
                        }

                        return values;
                    }, []);

                    let size = 300,
                        filter,
                        value = find(someValues, v => v.label === 'String');

                    filter = `neededValues.id=in=(${value})`;

                    return dispatch(fetchSomeOtherData({
                        size,
                        filter
                    }));
                });
        }
    ],
    mapStateToProps, {
        ...
    }
)(Component);
```
Guess the picture is clear. I need to fetch data, after that fetch another data. **Could you tell me please, is this code correct or may be there's another, *right* way?** And why params (which is route params?) are empty? 😞

**Comment by AVVS** [comment]
If you nest components then sequencing would be performed automatically, otherwise you solution is perfectly fine.

as for params - I believe it could be changed in the react-router, all the props are merely what's been passed to a component from the router, so you might want to check the router object. I dont remember the exact structure from the memory, you can always console.log on the opts in the promise to see what you get :)

**Comment by AVVS** [comment]
@ronar did you figure it out?

**Comment by ronar** [comment]
@AVVS yes. You comment have had an effect. Thanks! You could close it.

**Comment by rahuljain-tt** [comment]
Hi @ronar 
I have the same structure that you have mentioned. In case of client side rendering my component gets loaded as soon as fetchProducts() is resolve. AsyncConnect is not waiting for fetchSomeOtherData to be resolved.

Server side rendering is working with the same code.

@AVVS Any direction in this?

**Comment by AVVS** [comment]
nested components are resolved serially - so this is what you'd want to do

**Comment by rahuljain-tt** [comment]
No, I want my component to be render when my all nested dispatch are resolved.

scenario is we are creating dynamic UI, where layout gets loaded first(Parent dispatch) and then components data calls(nested dispatch) are made. I don't want to render my page until all component data is loaded. This is working in Server side rendering. But its breaking in Client side rendering as I have mentioned in above comment.

**Comment by AVVS** [comment]
track promises manually, your nested dispatches should return some sort of promises or thunks or whatever, which you can keep track of in the asyncConnect. Otherwise it has no knowledge of whats happening inside and cant really tell whether you are done loading or not. Ideally anything that triggers an async action and needs to be resolved - must be connected somehow to the asyncConnect
