### ISSUE TITLE
add support to load the reducer via redux-immutable

### ISSUE THREAD

**Issue by NourSammour** [makeomatic/redux-connect#15]
is there any plan to add support for immutable.js
the library didn't work well with redux-immutable related to isLoaded flag

Thanks for your awesome work

**Comment by AVVS** [comment]
I'm not familiar with immutable.js, so if you want to see it in here, please help me and explain the main concept behind it and what needs to be done to support it. Thanks

**Comment by NourSammour** [comment]
I used Immutable.js to be sure my states are immutable
and i'm thinking about add https://github.com/gajus/redux-immutable
so i can have one/global Immutable object
but the problem redux-connect don't support it
I'll do PR to add this feature (in a week)

follow this issue for more details
https://github.com/Rezonans/redux-async-connect/pull/45

**Comment by ruiaraujo** [comment]
@NourSammour we could ensure your states are immutable by using normal objects and using deepFreeze in your tests.

**Comment by sebastiancarlsson** [comment]
Maybe this could be an inspiration on how to achieve this: [react-router-redux](https://github.com/reactjs/react-router-redux#what-if-i-use-immutablejs-with-my-redux-store)

**Comment by MaxSvargal** [comment]
+1, have this problem too

**Comment by AVVS** [comment]
This is a pretty easy change to do, but I don't have time for it exactly right now. I'd be glad to merge a PR, @sebastiancarlsson provided a nice starting point on how to embed it here.

We need 2 things: 

- [ ] custom attach point; 
- [ ] reducer;

First one is an absolute must and is very easy to do, second one is a bit harder

**Comment by MaxSvargal** [comment]
@AVVS i see problems with finalMapStateToProps's .reduce() method and reducer.
i try to resolve this.

**Comment by AVVS** [comment]
@MaxSvargal yes, thats kind of tricky - we literally have to write an immutable-js compatible one

**Comment by MaxSvargal** [comment]
But now i think this https://github.com/rtfeldman/seamless-immutable is better solution.

**Comment by NSLS** [comment]
Is there any update on this issue? The questions seems to be relevant to me aswell

**Comment by AVVS** [comment]
@NSLS no update here, but PRs are always welcome

**Comment by NSLS** [comment]
@AVVS Is this PR going to be merged soon?

**Comment by AVVS** [comment]
Feature landed in https://github.com/makeomatic/redux-connect/tree/v3.0.0

**Comment by rkoberg** [comment]
Am I correct in seeing that this only applies to state stored under reduxAsyncConnect? That is if you use a "promise" AND a "key" property when setting up an object for the first argument in the asyncConnect call. If you do not use a "key" property, then this feature will not affect you, correct? 

I ask because I have been using a great deal of Records from ImmutableJS along with transit https://github.com/glenjamin/transit-immutable-js , specifically as constrained here https://github.com/este/este/blob/master/src/common/transit.js

I thought I had posted here about this issue when I first saw it, but apparently not. transit can do this job extremely well without having to maintain your own version. For example, how do you deal with serialization and deserialization of Records? What if someone defines a Record, but you (redux-connect) deserialize back into a Map (Is that what happens as implemented now?). This is is a little tricky. Records are one of the most important functions in immutable. You should enforce naming the Record, create a registry, yada yada.
