### ISSUE TITLE
Support server error

### ISSUE THREAD

**Issue by igoldny** [makeomatic/redux-connect#16]
currently when server render happens whether if it is was successful or not it will render then page with response status 200, but what if one of the promises failed?  we should have the ability to catch it and return server error.

`
     loadOnServer({ ...renderProps, store }).then(() => { SUCCESS }).catch(() => { FAILURE })
`

**Comment by AVVS** [comment]
You can perform check based on the store state in the current implementation, I can probably add "error" to topmost state, so that if `key` is undefined for the promise that failed you could still see it. As for the then/catch it would really be a breaking change and I don't see how useful it can be. Generally the error should've populated your state and your router should've reacted to it by redirecting and rendering an appropriate page

**Comment by igoldny** [comment]
Sounds good, thnx
