### ISSUE TITLE
Reloading data

### ISSUE THREAD

**Issue by joshgagnon** [makeomatic/redux-connect#24]
Firstly, thanks for creating this fork.

How would one go about refetching data?   E.g. after posting some update, invalidate the current response for some key and rerun the promise.  Currently I am just using react-router-redux -> replace (currentLocation)  but this seems particularly hacky.

Thoughts?

**Comment by AVVS** [comment]
On any route transition redux connect would re-run promises in all of the matched components, optionally filtered by filter func, returned by router.

If you want some of these actions to not refetch smth and use cached values - you should supply logic for it yourseld

**Comment by joshgagnon** [comment]
So if I want to refetch data for a component, (and if I'm using something like react-router-redux), then I must to do:
`dispatch(routeActions.replace(this.props.location)),`  (replace the location with the same location)
This seems a bit strange, although I suppose I could replace it with a 'refresh' HoC or something to make the intention clearer.

**Comment by AVVS** [comment]
This would refetch data for all components. You should abstract action to refetch data for a given component and call it in some action handler. Could you elaborate the use-case for refreshing data on the same URL?

**Comment by joshgagnon** [comment]
>"This would refetch data for all components."
Would it?  Only if I have set store.reduxAsyncConnect.loadState[SOME_KEY].loaded = false, right?

The use cases I have are as follows:
* Submitting a form, but then continuing to show the same page with updated data (e.g edit some user details on a user details page, submit/save but keep me on this page)
* Periodically updating some semi-live data.

In my case, updating/creating/deleting a resource invalidates large parts of the store, so there are too many resources to keep track of to manually refresh. Rerunning the promises for every component will fetch all the invalided resources, and so at least seems like the appropriate approach.

**Comment by AVVS** [comment]
> Would it? Only if I have set store.reduxAsyncConnect.loadState[SOME_KEY].loaded = false, right?

Not really. This is not widely used and should be fixed when adding more granularity to checks, this key is for you to understand where data had been fetched or not (based on the provided `filter` function, which is noop by default)

[Begin global load](https://github.com/makeomatic/redux-connect/blob/master/modules/store.js#L17-L20) action clears state and is invoked by [componentWillReceiveProps](https://github.com/makeomatic/redux-connect/blob/master/modules/components/AsyncConnect.js#L44), which in turn is invoked whenever the route is changed, because router will trigger a transition and run a render on the underlaying components

> Submitting a form, but then continuing to show the same page with updated data (e.g edit some user details on a user details page, submit/save but keep me on this page)

Best practice is to handle loading of a user with an appropriate action. You already should have all the logic to handle user updates in the app and reloading is certainly not an answer to this. What you have to do is dispatch same action as you would normally do after user had finished loading in the form onSuccess action (I assume you use redux-form version 6+), then it will trigger chain of events by itself and you wont need to really care about that.

In case you still dont want to be bothered with it, well, refresh the page by using `push` action from react-router-redux, but then again I dont see why it would be needed

> Periodically updating some semi-live data.

Again, it's best to _not_ refetch all the data, but simply write a redux module handling that or add logic to each of your modules for fetching periodic updates and handle it with your reducers

Does it make sense?

**Comment by joshgagnon** [comment]
Yeah this make sense.
Thanks.

**Comment by AVVS** [comment]
glad I could help :)

**Comment by yanivel** [comment]
Another use case is when we load the same route but with a different, let's say, router param, which causes the async promise to invoke again (let's say there's one in the AsyncProps). 
If I dispatch several actions and afterwards resolve the promise, the component will immediately rerender if one of the props have changed because of a dispatch, even before the promise resolved. If we dispatch several actions in the AsyncProps promise, the component is in an unknown state in between dispatches, and possible errors because.

I could clear the key before reloading the route (right?) but I cannot import the action from the library, and even if I could, I would want it as a part of the AsyncProp itself (as options?) to make it block rerendering (I thought this is what automatically happens if the stateToPropMap is used inside the decorator).
