### ISSUE TITLE
Future plans question

### ISSUE THREAD

**Issue by apomortsev** [makeomatic/redux-connect#4]
Hello,

Will this project from now on be maintained independently from redux-async-connect or will it be eventually merged back? Will any future redux-async-connect changes be merged or otherwise integrated here?

Thanks

**Comment by AVVS** [comment]
Because there was no traction, nor any answers to dozens of questions on the previous repo - I made the decision to refactor the codebase and maintain it myself. Redux-connect used in multiple projects I'm working with and that should alone be enough to support this going forward. 

As always, I'd gladly welcome other contributors that would help maintain this - part of the OSS being successful is a great community around it. I hope this answered your question. 

As for the dev plans themselves - I want to hear more about use-cases that are not supported, or something that takes up too much code. One of the ideas is to make an automatic `isLoaded` check - it's often controversial though.

**Comment by AVVS** [comment]
Closing this, hopefully it resolved your question
