### ISSUE TITLE
redirect via router

### ISSUE THREAD

**Issue by mmahalwy** [makeomatic/redux-connect#48]
Given @asyncConnect loads some sort of resource to load in redux... what happens if API returns 404? Need to redirect to another page.

**Comment by AVVS** [comment]
you should dispatch redirect action to 404 as part of your promise handling logic, or set state to 404 and make use of parent component who binds to status and renders error page instead of other components. in any case this must be done in the application you write and there are many ways to achieve it

**Comment by AVVS** [comment]
are we good here?

**Comment by mmahalwy** [comment]
yep, thanks @AVVS
