### ISSUE TITLE
ReduxConnect breaks hot reloading with server side rendering

### ISSUE THREAD

**Issue by michalg42** [makeomatic/redux-connect#7]
Hello
Yesterday I changed redux-async-connect to redux-connect in my project and I noticed that it broke hot reloading. Part of code that was calculated on server side never changes, in opposite to client side.
I'm using this project: https://github.com/erikras/react-redux-universal-hot-example as my boilerplate and on clean version of this project it works fine (I added console.log to code and after hot reload it showed my message), when I changed there redux-async-connect on redux-connect I did the same thing - and in order to display my console.log in terminal I had to quit process and start it again, just refreshing page wasn't enough.

**Comment by hanjukim** [comment]
@michalg42 Based on my investigation, RRUHE's action handling was core cause of wrong SSR result.
https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/redux/middleware/clientMiddleware.js#L13 In here, redux-async-connect recognise promise has been finished when REQUEST promise is done, not after SUCCESS or FAILURE has been finished. Therefore, SSR result is in middle of REQUEST and SUCCESS || FAILURE. I wish my case was helpful.

**Comment by AVVS** [comment]
@michalg42 I haven't looked at https://github.com/erikras/react-redux-universal-hot-example, but as @hanjukim stated, you have to return _last_ promise from the chain, so that you really have the complete state after all of the promises are done resolving.

Furthermore, there is 1 adjustment that had been done compared to original `redux-async-connect` - promises that are gathered from async components are processed sequentially, this is done to allow nested components to rely on state from parent components

If that answered your question or helped you in any way - please consider adding a note to readme,
thanks.

**Comment by AVVS** [comment]
If you have more questions - feel free to ask. Closing for now
