### ISSUE TITLE
Parent container is blocked from rendering

### ISSUE THREAD

**Issue by danbovey** [makeomatic/redux-connect#87]
I had redux-async-connect setup to show a progress bar while it was global loading. I actually commented about the setup on a [PR to do with blocking etc](https://github.com/makeomatic/redux-connect/pull/20#issuecomment-223780497) when it was working!

I Switched to redux-connect because it stopped working, I thought a further developed fork would help out but, despite the component being outside of the async container, it's no longer rendering straight away.

The wrapper container used to show a loading page and the child container asyncConnect'ed the auth user. But now it's blocking the render of the parent container/component until `@redux-conn/LOAD_SUCCESS` is complete.

```js
<Route component={AppWrapper}>
    <Route component={App}>
        // containers
    </Route>
</Route>
```

AppWrapper
```js
@connect(
    state => ({
        loaded: state.reduxAsyncConnect.loaded
    })
)
```

App
```js
@asyncConnect([{
    key: 'auth',
    promise: ({ store: { dispatch, getState }, helpers }) => {
        if(!isAuthReady(getState())) {
            return authLoad()(dispatch);
        } else {
            return new Promise((resolve) => resolve(getState.auth));
        }
    }
}])
```

There might not be anything wrong with the library but I'd appreciate some help here. Should it stop the rendering of AppWrapper even though it's below it in hierarchy of Routes?

Thanks for keeping this maintained!

**Comment by AVVS** [comment]
To load a rendered you need to provide your custom rendered instead of ReduxAsyncConnect component, which does not show anything while stuff loads. However, there is no point to do that, because this module aims to provide server side rendering, and, frankly - server side rendering cant return a loader as you will be providing this content to search engines.

Being said that - you either dont need this module at all, or there is a need to read up more on the redux, async actions, loaders and state. You should be connecting loading prop to your loader and react will render this. When loading is done you dispatch another action and set loading to false, which hides the loader and shows content. But this is for SPA, not SSR. In either case while redux did not load completely - nothing will get rendered, and it is the core of this module more or less

**Comment by danbovey** [comment]
OK thanks. Yeah, I think I just need to rethink stuff. I learnt basically everything I know about redux from [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/containers/App/App.js) but maybe it's not the best.
